version: "3"
services:
  server:
    build: .
    command: cat
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
    tty: true

  client1:
    build: .
    command: cat
    depends_on:
      - "server"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
    tty: true

  client2:
    build: .
    command: cat
    depends_on:
      - "server"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
    tty: true


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
