//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `types.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package types.Smarthouse;

/** @hidden */
public class _DeviceCloudPrxI extends com.zeroc.Ice._ObjectPrxI implements DeviceCloudPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
