//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `types.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package types.Smarthouse;

interface _Marker
{
}
