//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `types.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package server.src.main.java.Smarthouse;

/** @hidden */
public class _WihajsterPrxI extends com.zeroc.Ice._ObjectPrxI implements WihajsterPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
